sudo: false
language: node_js
node_js:
  - '7'
  - '6'
  - '4'
services:
  - memcached
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
